# -*- coding: utf-8 -*-
"""restaurante_online.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HihlfEgjVmrVu23QRUvaBIPnGPUBq0uA
"""

""" En una hamburguesería han abierto la posibilidad de hacer pedidos online. Ofrecen básicamente
dos productos de fama mundial: su hamburguesa clásica y la hamburguesa vegana.
Los ingredientes extra de la hamburguesa clásica son:- Queso Idiazabal- Bacon- Huevo
 Los ingredientes extra de la hamburguesa vegana son:- Tofu- Cebolla caramelizada
 Crea un script que le pregunte al usuario que tipo de hamburguesa quiere. En función de la
respuesta debe enseñarle los ingredientes extra disponibles y permitirle escoger uno de ellos.
Finalmente debe imprimir por pantalla que tipo de hamburguesa se ha elegido y cuales son sus
ingredientes."""

hamburguesa = input("¿Que tipo de hamburguesa quieres? (Clasica/Vegana): ").strip().lower()

if hamburguesa == "clasica":
    extra= input("Puedes elegir un ingrediente extra entre queso, bacon, huevo, nada : ").strip().lower()

    if extra== "queso":
     print("De acuerdo, has elegido hamburguesa clásica con", extra)

    elif extra== "bacon":
     print("De acuerdo, has elegido hamburguesa clásica con", extra)

    elif extra== "huevo":
     print("De acuerdo, has elegido hamburguesa clásica con", extra)

    elif extra== "nada":
     print("De acuerdo, has elegido hamburguesa clásica con", extra)
    else:
      print("El extra elegido es erroneo")

elif hamburguesa == "vegana":
    extra_vegana= input("Puedes elegir un ingrediente extra entre tofu, cebolla caramelizada, o nada : ").strip().lower()

    if extra_vegana== "tofu":
     print("De acuerdo, has elegido hamburguesa vegana con", extra_vegana)

    elif extra_vegana== "cebolla caramelizada":
     print("De acuerdo, has elegido hamburguesa vegana con", extra_vegana)

    elif extra_vegana== "nada":
     print("De acuerdo, has elegido hamburguesa vegana con", extra_vegana)
    else:
      print("El extra elegido es erroneo")

else:

  print("El tipo de hamburguesa elegido es erroneo")