# -*- coding: utf-8 -*-
"""duplicar_caracteres.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/191nRqPdVDpfZp1m6cki-HlkqPcqO1wqp
"""

"""Crea un script que acepte un string de 5 caracteres y devuelva otro string con todos los caracteres
duplicados. Si el input es ‘sbc56’, el output deberá ser ‘ssbbcc5566"""

cadena_caracteres = input("Introduce una cadena de 5 caracteres: ")

#verifica q la cadena tiene realmente 5 caracteres
if 1<= len(cadena_caracteres) <= 5:
    cadena_duplicada = ""
    for caracter in cadena_caracteres:
        cadena_duplicada += caracter * 2
    print(cadena_duplicada)

else:
      print("Error: Debes introducir entre 1 y 5 caracteres.")