# -*- coding: utf-8 -*-
"""numero_tarjeta.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Hgo57cvvxvYaTHOReBYHa1Gy01JXdF9J
"""

"""Crea un script que reciba como input un número de tarjeta de crédito e imprima por pantalla todos
los caracteres en forma de asterisco salvo los últimos cuatro. Si por ejemplo el número de tarjeta
es 1234 2345 3456 5678, el output deberá ser **** **** **** 5678."""

numero_tarjeta =input("Ingresa un número de tarjeta de crédito: ")

num_modificado = numero_tarjeta[:-4].replace(numero_tarjeta[:-4],"*" * len(numero_tarjeta[:-4]) + numero_tarjeta[-4:])

#num_tarjeta[:-4] seleccionamos todos los diitos menos los 4 ultimos
#.replace() reemplazamos tods esos numeros por *
# *len(num_tarjeta:-4) multiplica el * por el numero de caracteres q tenemos en num_tarjeta[:-4]
#tarjeta [-4:] deja los ultimos4 caracteres sin cambiar

print(num_modificado)