# -*- coding: utf-8 -*-
"""restaurante.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yQSEfBaYCc5eM_WZK_2Q-Ryh8HQZJ1TT
"""

""" En un restaurante el menú consta de las siguientes opciones:
 Ensalada mixta   ————————   12 EU
Sopa de pescado    ———————   10 EU
 Dorada al horno  ————————   18 EU
 Arroz al curry  —————————   14 EU
 Lasaña de carne     ———————   15 EU
 Brownie de chocolate    —————    8 EU
 Helado    ———————————    6 EU
 Refrescos    ——————————    5,5 EU
 Café    ————————————    3,5 EU
 Escribe un script que lea la cantidad de cada alimento consumido y que calcule e imprima el total
de la cuenta."""

#declaramos todos los productos y su precio (inicializamos?)
ensalada = 12
sopa = 10
dorada = 18
arroz = 14
lasaña = 15
brownie = 8
helado = 6
refresco = 5.5
cafe = 3.5

#preguntamos producto por producto el número q se han consumido

num_ensalada = float(input("Introduce el número de ensaladas: "))
num_sopa = float(input("Introduce el número de sopas: "))
num_dorada = float(input("Introduce el número de doradas: "))
num_arroz = float(input("Introduce el número de arroz: "))
num_lasaña = float(input("Introduce el número de lasaña: "))
num_brownie = float(input("Introduce el número de brownies: "))
num_helado = float(input("Introduce el número de helados: "))
num_refresco = float(input("Introduce el número de refrescos: "))
num_cafe = float(input("Introduce el número de cafes: "))

#claculamos el total, multiplicando el numero por el producto y sumando- e imprimimos

total = (ensalada * num_ensalada) + (sopa * num_sopa) + (dorada * num_dorada) + (arroz * num_arroz) + (lasaña * num_lasaña) + (brownie * num_brownie) + (helado * num_helado) + (refresco * num_refresco) + (cafe * num_cafe)
print("El total de la cuenta es: ", total, "€")