# -*- coding: utf-8 -*-
"""7_validacion_form.(BIS).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1b5n8KcTTThxz1dbAxyKW815dxrYCUfKK

VALIDACIÓN DE FORMULARIO Crea un programa que valide un formulario de registro. Crea una función llamada validar_formulario que reciba diferentes campos de un formulario (nombre, correo electrónico y número de teléfono) y verifique si los valores ingresados cumplen con los requisitos especificados, siendo estos:

Que el nombre tenga una longitud minima de 3 caracteres
Que el teléfono este conformado por dígitos y tenga una longitud de 9 caracteres
Que el email contenga un “@“ y un “.”
"""

#repetido metiendo el return dentro de la funcion

def validar_formulario(nombre, mail, num_telefono):
    if len(nombre) < 3:
        print("El nombre debe tener al menos 3 caracteres.")
        return None
    if "@" not in mail or "." not in mail:
        print("El correo electrónico debe contener '@' y '.'.")
        return None
    if not num_telefono.isdigit() or len(num_telefono) != 9:
        print("El teléfono debe tener 9 dígitos y solo números.")
        return None
    return {"nombre": nombre, "correo": mail, "teléfono": num_telefono}

#Repetimos hasta que la función devuelva un diccionario (es decir, datos válidos)
datos = None
while datos is None:
    nombre = input("Introduce tu nombre: ")
    correo = input("Introduce un correo electrónico: ")
    telefono = input("Introduce tu número de teléfono: ")
    datos = validar_formulario(nombre, correo, telefono)
    if datos is None:
        print("Datos incorrectos, por favor vuelve a introducirlos.\n")

print("Formulario válido:", datos)